### ISSUE TITLE
Captcha integration for the Laravel

### ISSUE THREAD

**Issue by Japoivvb** [Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital#171]
investigate how to integrate it in the project, e.g. before to send a book appointment in home page, a cpatcha must be done to allow send the request

**Comment by Omirzar1337** [comment]
I've found this docs that look really promising. I'll continue to inform

https://coderflex.com/blog/enhancing-security-and-user-experience-leveraging-recaptcha-with-laravel-and-livewire

**Comment by Japoivvb** [comment]
> I've found this docs that look really promising. I'll continue to inform
> 
> https://coderflex.com/blog/enhancing-security-and-user-experience-leveraging-recaptcha-with-laravel-and-livewire

Ok, I had a look and you were right, main problem is captchav3 is not calling at any moment to corresponding function updateCaptchad() in controller so add_contact() is not able to evaluate attribute $this->captcha
What I did using your useful link is implement a POC with v2 although then user must check grecaptcha to allow continue the flow. For academic purpose I think even is better if other developers see the functionality v2 working, v3 is too much automatic/invisible to learn about it. 

if no check in form
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/350a80c3-e712-4a0d-a4b9-1c4b380bbca7)
return some error to home view, now using dd
![image](https://github.com/Stucom-Pelai/DAW2_M07_UF3_Eloquent-Hospital/assets/36648472/55910831-3dfe-48db-8f34-93a15b0e5c3e)
I did the commit with POC, so test it in your side, if you agree and it is fine please

1. adapt blade to have a better form design
2. clean an format code
3. implement better error handling when no check
4. adapt .env.example and .env with KEYs
5. merge in main and mov to QA

Once everything done, we can do similar solution in other form by other developer to share the knowledge.

**Comment by Omirzar1337** [comment]
Oh, it looks great! Thanks for the hard work, I know it is a headache to implement ReCaptcha 😂 
To be fair, I must say I liked better the V3 ReCaptcha but I agree that V2 allows for a better understanding and learning although it is kind of invasive

I'll carry on with the points  you mentioned (I'll write them down this comment in order to be able to mantain some order in my messed head 🤯)

I'll let you know when everything is ready in order for you to check it ✔️ 

Once again, thanks

- [ ] adapt blade to have a better form design
- [ ] clean an format code
- [ ] implement better error handling when no check
- [ ] adapt .env.example and .env with KEYs
- [ ] merge in main and mov to QA

**Comment by Omirzar1337** [comment]
Regarding the fourth point I wrote the environment variables and used your keys so everyone would be able to use them. Is this the expected behaviour??
